version: "3"

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: python-docker-template
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./docker/python/.env
    ports:
      - "8888:8888"
    volumes:
      - ./source:/usr/src/source
    working_dir: /usr/src/source
    tty: true
